# This is a basic workflow to help you get started with Actions

name: Format


# Controls when the workflow will run
on: [push, pull_request, workflow_dispatch]

  # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  format:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Google Java Format
        uses: axel-op/googlejavaformat-action@3.5.0

