# This is a basic workflow to help you get started with Actions

name: Prepare Abgabe files

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  prepareFiles:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Create temp directory for release files
        run: mkdir release

      # Runs a single command using the runners shell
      - name: Remove package declarations
        run: for FILE in *.java; do echo "$FILE"; tail -n +3 "$FILE" > release/"$FILE"; done
      
      - name: Remove leading blank lines
        run: for FILE in release/*.java; do sed '/./,$!d' "$FILE"; done

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: java_05_h
          path: release/
