# This is a basic workflow to help you get started with Actions

name: Prepare Abgabe files

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  prepareFiles:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Remove package declarations and leading blank lines
        run: |
          for FILE in *.java; do
            [ -f "$i" ] || break
            mkdir temp
            tail -n +3 "$FILE" > "temp/$FILE.tmp"
            sed '/./,$!d' "temp/$FILE.tmp"
            mv "temp/$FILE.tmp" "temp/$FILE"
          done

      - uses: papeloto/action-zip@v1
        with:
          files: temp/
          dest: abgabe_05_h.zip
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
    
      - name: Remove temporary files
        run: |
          rm -rf temp/
